### ISSUE TITLE
Add Mirasvit MstCore Observers

### ISSUE THREAD

**Issue by josh-carter** [digitalpianism/nocallhome#2]
Quite well documented here by [steverobbins](https://github.com/steverobbins/Magento-PhoneHomeList/tree/master/Mirasvit_MstCore)

[Pull Request #1](https://github.com/digitalpianism/nocallhome/pull/1)

**Comment by digitalpianism** [comment]
@josh-carter awesome I didn't know that repo thanks for that =)

**Comment by josh-carter** [comment]
@digitalpianism your welcome! Yer its perfect for this extension.

**Comment by digitalpianism** [comment]
@josh-carter I made more updates and used a little trick to ensure this module always "wins" over the home caller ;)

**Comment by josh-carter** [comment]
@digitalpianism Ah sneaky. I'll put that one in the notepad!
